language: python
dist: xenial
python:
  - 3.6

cache: pip

matrix:
  include:      
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      install:
        - cd deps
        - git clone https://github.com/QE-Lab/libqasm.git
        - cd libqasm
        - pip install . 
        - cd ..
        - git clone https://github.com/QE-Lab/eQASM_Assembler.git
        - cd eQASM_Assembler/qisa-as
        - git checkout development
        - pip install .
        - cd ../../../.
        - pip install .
      script: python3 -m pytest


before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
install:
  - cd deps
  - git clone https://github.com/QE-Lab/libqasm.git
  - cd libqasm
  - pip install . 
  - cd ..
  - git clone https://github.com/QE-Lab/eQASM_Assembler.git
  - cd eQASM_Assembler/qisa-as
  - git checkout development
  - pip install .
  - cd ../../../.
  - pip install .
script: python3 -m pytest


addons:
  apt:
    packages:
      - cmake
      - swig
      - flex
      - bison
  homebrew:
    packages:
      - cmake
      - swig
      - flex
      - bison
    update: true
