language: python
sudo: false
dist: xenial

os:
  - linux

python:
  - "3.6"

cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest

install:
  - cd deps
  - pwd
  - git clone https://github.com/QE-Lab/libqasm.git
  - cd libqasm
  - pwd
  - pip install . 
  - cd ../..
  - pwd
  - pip install .

script: pytest

addons:
  apt:
    packages:
      - swig
      - flex
      - bison
  homebrew:
    packages:
      - swig
      - cmake
    update: true
